const invoiceActionTypes = {
  GET_ALL_INVOICES: "@invoices/GET_ALL_INVOICES",
  CREATE_INVOICE: "@invoices/CREATE_INVOICE",
  GET_INVOICE_DETAILS: "@invoices/GET_INVOICE_DETAILS",
  DELETE_INVOICE: "@invoices/DELETE_INVOICE",
  GET_RECURRING_INVOICES: "@invoices/GET_RECURRING_INVOICES",
  EDIT_INVOICE: "@invoices/EDIT_INVOICE",
  END_RECURRING_INVOICE: "@invoices/END_RECURRING_INVOICE",
  GET_YEARLY_DATA: "@invoices/GET_YEARLY_DATA",
  GET_CASHFLOW_DATA: "@invoices/GET_CASHFLOW_DATA",
};

export default invoiceActionTypes;
